### ISSUE TITLE
Can you provide a learnable demo？

### ISSUE THREAD

**Issue by sunny-lp520** [KumarRobotics/MOCHA#4]
Thank you very much for sharing. I am a beginner in air-ground collaboration and am very interested in your work. Can you share some complete demos to learn?

**Comment by fcladera** [comment]
Hi! 

We released yesterday our full stack: https://github.com/KumarRobotics/spomp-system

MOCHA is the communications piece of this stack. I encourage you to check this repo!

**Comment by sunny-lp520** [comment]
> Hi! We released yesterday our full stack: https://github.com/KumarRobotics/spomp-system MOCHA is the communications piece of this stack. I encourage you to check this repo!
> […](#)
> On October 30, 2023 8:03:37 AM EDT, sunny-lp520 ***@***.***> wrote: Thank you very much for sharing. I am a beginner in air-ground collaboration and am very interested in your work. Can you share some complete demos to learn? -- Reply to this email directly or view it on GitHub: #4 You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>
Thank you very much, you are really amazing. This job is really outstanding and has been very helpful to me. Thank you again.
